apiVersion: v1
kind: Service
metadata:
  name: vote-preview
  labels:
    role: vote
spec:
  selector:
    app: vote
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30100
  type: NodePort
